bashak/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',include('core.urls',namespace='core')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, documet_root = settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views
from core.views import (
    IndexListView,
    SectorDetailView,
    ContactCreateView,
    CareerListView,
    CareerDetailView,
    InnovationsListView,
    InnovationsDetailView,
    KorporativCategoryListView,
    KorporativCategoryDetailView,
    
)

app_name = 'core'

urlpatterns = [
    path("career/", CareerListView.as_view(), name="career"),
    path("career/<slug:slug>/", CareerDetailView.as_view(), name="career_detail"),
    path("innovations/", InnovationsListView.as_view(), name="innovations"),
    path("innovations/<slug:slug>/", InnovationsDetailView.as_view(), name="innovations_details"),
    # path("", views.index,name='index'),
    path("", IndexListView.as_view(), name="index"),
    path("corporative/", KorporativCategoryListView.as_view(), name="korporative"),
    
    path("sector/<slug:slug>/", SectorDetailView.as_view(), name="sector_detail"),
    path("corporative/team/<slug:slug>/", KorporativCategoryDetailView.as_view(), name="korporative_detail"),
    
    
    
    path("contact/", ContactCreateView.as_view(), name="contact"),
    
    
]

core/models.py
from distutils.command.upload import upload
from itertools import count
import re
from tkinter import N
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.safestring import mark_safe

from django.urls import reverse
from django.utils import timezone


# Create your models here.



class Korporativ(models.Model):
    description = models.TextField(max_length=3000)
    
    def __str__(self):
        return self.description
    
    
    class Meta:
        verbose_name_plural = 'Korporativ'
        
        


class KorporativCategory(models.Model):
    #relations 
    category=models.ForeignKey('self',db_index=True,blank=True,null=True,related_name='categories',on_delete=models.CASCADE)
    
    
    title = models.CharField(max_length=120)
    image = models.ImageField(upload_to='media',default='IMG.JPG', blank=True,null=True)
    content = RichTextUploadingField(blank=True, null=True)
    slug = models.CharField(max_length=300, verbose_name='Slug', unique=True, blank=True, null=True)
    
    
    
    def __str__(self):
        if self.category:
            return f"{self.category.title} > {self.title}"
        return self.title 
            
    
    
    def get_absolute_url(self):
        return reverse("core:korporative_detail", kwargs={"slug": self.slug})
    
    
    
    def image_tag(self):
        return mark_safe('<img src="{}" height="100" width="100"/>'.format(self.image.url))
    
    class Meta:
        verbose_name_plural = 'Esas Category'
        
    class Meta:
       ordering = ('id',)
    
    

        
        
    
    
        
        
class RehberlikCategory(models.Model):
    
    korporativcategory = models.ForeignKey('KorporativCategory',on_delete=models.SET_NULL,related_name='team_detail',blank=True,null=True)
    position = models.CharField(max_length=200)
    full_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='media')
    
    facebook_link  = models.CharField(max_length=120,blank=True,null=True)
    linkedin_link  = models.CharField(max_length=120,blank=True,null=True)
    
    def image_tag(self):
        return mark_safe('<img src="{}" height="100" width="100"/>'.format(self.image.url))
        
    
    def __str__(self):
        return self.full_name
    
    def get_absolute_url(self):
        return reverse("core:korporative_detail", kwargs={"slug": self.slug})
    
    class Meta:
        verbose_name_plural = 'Rehberlik Team'
        
        
    
    
    


        
    



    
    
    
    





class Address(models.Model):
    address = models.CharField(max_length=200,default='Bakı şəhəri, Ziya Bünyadov prospekti 3105-ci məhəllə')
    phone_number1 = models.CharField(max_length=200,default='+994 70 252 11 16')
    phone_number2 = models.CharField(max_length=200,default='+994 50 888 18 88')
    phone_number3 = models.CharField(max_length=200,default='+994 12 511 51 57')
    email = models.EmailField(default='info@bashakgroup.az',blank=True)
    
    
    def __str__(self):
        return self.address

    class Meta:
        verbose_name_plural = 'Address'
        
        

class Career(models.Model):
    
    
    position = models.CharField(max_length=200,verbose_name='vəzifə')
    requirements = RichTextUploadingField()
    obligations = RichTextUploadingField()
    working_conditions = RichTextUploadingField()
    slug = models.SlugField(max_length=300, verbose_name='Slug', unique=True, blank=True, null=True,allow_unicode = True,)

    
    def __str__(self):
        return self.position
    
    
    def get_absolute_url(self):
        return reverse("core:career_detail", kwargs={
            "slug": self.slug
        })
    
    
    class Meta:
        verbose_name_plural = 'Karyera'
        
        

    
class CareerCsv(models.Model):
    career = models.ForeignKey('Career',on_delete=models.CASCADE,related_name='careers',blank=True,null=True)
    
    full_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=120)
    
    cv = models.FileField(upload_to='career/cvler/',blank=True,null=True)
    
    
    def __str__(self):
        return str(self.career) 
    
    
    

class Contact(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField(max_length=120)
    phone = models.CharField(max_length=80)
    message = models.TextField(max_length=1000)
    
    created_at = models.DateTimeField(auto_now_add=True,blank=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Əlaqə'



class About(models.Model):
    haqqımızda = models.TextField(max_length=3000)
    
    def __str__(self):
        return self.haqqımızda
    
    
    
    class Meta:
        verbose_name_plural = 'Haqqımızda'

    
    
class Innovations(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=2000)
    content = RichTextUploadingField()
    news_image = models.ImageField(upload_to='media')
    slug = models.CharField(max_length=300, verbose_name='Slug', unique=True, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    is_published = models.BooleanField(default=False)
    main_news = models.BooleanField(default=False)
    
    class Meta:
        verbose_name_plural = 'Innovations'
    
    
    
    
    def image_tag(self):
        return mark_safe('<img src="{}" height="100" width="100"/>'.format(self.news_image.url))


    def get_absolute_url(self):
        return reverse("core:innovations_details", kwargs={"slug": self.slug})
    

    def __str__(self):
        return self.title
    
    
        
    
  

class Sector(models.Model):
    #relations
    count = models.IntegerField()
    title = models.CharField(max_length=120)
    description = models.TextField(max_length=2000)
    general = RichTextUploadingField()
    slug = models.CharField(max_length=300, verbose_name='Slug', unique=True, blank=True, null=True)
    
    sector_image = models.ImageField(upload_to='media')
    

    
    def __str__(self):
        return self.title
    
    
    def get_absolute_url(self):
        return reverse("core:sector_detail", kwargs={
            "slug": self.slug
        })
    
    def image_tag(self):
        return mark_safe('<img src="{}" height="100" width="100"/>'.format(self.sector_image.url))
    
    
    
    class Meta:
       ordering = ['count',]



    
    
    
class CategoryDesign(models.Model):
    category_design = models.ForeignKey('Sector',on_delete=models.CASCADE,blank=True,null=True,related_name='categories_design')
    
    title = models.CharField(max_length=120)
    description = models.TextField(max_length=1000)
    
    image = models.ImageField(upload_to='media')
    
    class Meta:
        verbose_name_plural = 'CategoriesDesign'
        
        
    def __str__(self):
        return self.title
    
    
    def image_tag(self):
        return mark_safe('<img src="{}" height="100" width="100"/>'.format(self.image.url))
    



    

core/forms.py
from turtle import position
from django import forms
from .models import Career, CareerCsv, Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = (
            'name',
            'email',
            'phone',
            'message',
        )
        
        
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'name-surname'
                }),
            
            
            'email': forms.EmailInput(attrs={
                'class':'email1'
                
                }),
            
            'phone':forms.TextInput(attrs={
                'class':'phone'
                
                }),

            
            
            'message': forms.Textarea(attrs={
                'class': 'textarea'
            })
        }
        
        
        



class CareerCvForm(forms.ModelForm):

    class Meta:
        model = CareerCsv
        fields = [
            'career',
           
        ]
        
        widgets = {
            
            'career':forms.TextInput(attrs={
                        'class':'vakant',
                        'placeholder': 'VAKANT YER',
                        'empty_label':"VAKANT YER",
                    }),
        }
        


class CareerForm(forms.ModelForm):
    
    
    
    
    class Meta:
        model = CareerCsv
        fields = [
            'career',
            'full_name',
            'email',
            'cv',
        ]
        
        

        
        
    
        widgets = {
            
            'career':forms.HiddenInput(attrs={
                        'class':'vakant',
                        'placeholder': 'VAKANT YER',
                    }),
            
            'full_name':forms.TextInput(attrs={
                        'class':'vakant',
                        'placeholder': 'Ad,Soyad, Ata adı',
                        
                        
                    }),
            
            'email':forms.EmailInput(attrs={
                        'class':'vakant',
                        'placeholder': 'E-mail'
                    }),
        }

            
            

        
        
    
    
        

core/views.py
from django.views.generic.edit import FormMixin
from django.shortcuts import render, get_object_or_404, redirect

from django.views.generic import ListView,CreateView
from django.views.generic.detail import DetailView
from django.contrib.messages.views import SuccessMessageMixin
from .models import About, Career, CareerCsv, Contact,Address, Innovations, Korporativ, KorporativCategory, RehberlikCategory, Sector
from .forms import  CareerCvForm, CareerForm, ContactForm
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import render
# from .forms import CareerForm






# def index(request,category_slug=None):
#     category=None
#     categories_sektor = []
    
    
#     categories_list = CategorySektor.objects.all()
    
    
    
#     if category_slug:
#         categories_sektor=CategorySektor.objects.all()
#         category=get_object_or_404(CategorySektor,slug=category_slug)
#         categories_sektor=CategorySektor.objects.filter(name=category)
    

        
#     context = {
#         'categories_sektor':categories_sektor,
#         'categories_list':categories_list,
#     }
        
    
#     return render(request,'index.html',context)


class IndexListView(ListView):
    model = Sector
    template_name = 'index.html'
    context_object = 'sector_list'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sector_list"] = Sector.objects.all()
        context["innovations_list"] = Innovations.objects.all()
        context["address_list"] = Address.objects.all()[:1]
        
        
        
        
        return context
    

    
    
class SectorDetailView(DetailView):
    model = Sector
    template_name = 'sectors.html'
    success_url = reverse_lazy("core:index")
    




class CareerListView(ListView):
    model = Career
    template_name = 'career.html'
    
    


class CareerDetailView(SuccessMessageMixin,FormMixin,DetailView):
    template_name = 'vacancy-details.html'
    model = Career
    form_class = CareerForm
    success_message = 'Your resume has been accepted and will be returned to you!'
    error_message = 'Invalid form submission.'


    def get_success_url(self):
        return reverse('core:career_detail', kwargs={'slug': self.object.slug})    


       
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["about_list"] = About.objects.all()[:1]
        context["forms"] = CareerForm(initial={'career':self.object})
        context["for"] = CareerCvForm(initial={'career':self.object.position})
        
        
        
        return context
        
        
        
        
    
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def form_valid(self, form):
        form.save()
        return super(CareerDetailView, self).form_valid(form)
    
    def form_invalid(self,form):
        context = super().form_invalid(form)
        return context
    
        
    
    


# def upload_file(request):
#     if request.method == 'POST':
#         form = CareerForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('core:contact')
#     else:
#         form = CareerForm()
#     return render(request, 'vacancy-details.html', {'form': form})




class InnovationsListView(ListView):
    model = Innovations
    template_name = 'innovations.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["main_news_list"] = Innovations.objects.filter(main_news=True)
        return context
    
    
class InnovationsDetailView(DetailView):
    model = Innovations
    template_name = 'innovations-details.html'
    success_url = reverse_lazy("core:innovations_details")
    
    
    





# Create your views here.

class ContactCreateView(SuccessMessageMixin,CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'contact.html'
    success_message = 'Contact request submitted successfully!'
    error_message = 'Invalid form submission.'
    success_url = reverse_lazy('core:contact')
    
    
    def form_valid(self, form):
    #     message = "{name} / {email} said: ".format(
    #     name=form.cleaned_data.get('name'),
    #     email=form.cleaned_data.get('email'))
    #     message += "\n\n{0}".format(form.cleaned_data.get('message'))
        
        
        
    #     subject = 'Message subject'
    #     send_mail(
    #     subject,
    #     message=message,
    #     from_email='elish777888999@gmail.com',
    #     recipient_list=[settings.EMAIL_HOST_USER],
    #     fail_silently=False
        
    # )
        form.save()
        context =  super().form_valid(form)
        return context
    
    def form_invalid(self,form):
        self.messages.error(self.request,self.error_message)
        context = super().form_invalid(form)
        return context
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["address_list"] = Address.objects.all()[:1]
        return context    

    
    
class KorporativCategoryListView(ListView):
    model = KorporativCategory
    template_name='corporative.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["korporativ_list"] = Korporativ.objects.all()
        context["rehberlikcategory_list"] = RehberlikCategory.objects.all()
        
        
        return context
    
    
 
class KorporativCategoryDetailView(DetailView):
    model = KorporativCategory
    template_name='team.html'
    success_url = reverse_lazy("core:korporative_detail")
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rehberlikcategory"] = RehberlikCategory.objects.all()
        context["rehberlikcategory_list"] = RehberlikCategory.objects.all()
        
        
        return context
    
      
    

core/templates/innovations-details.html
{% load static i18n %}
{% load thumbnail %}
{% load custom_tags %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.green.min.css">
 

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <title>Bashak</title>
</head>
<body>

    <header>
        <nav class="scrolling2">
            <div class="navbar">
                <div class="logo change-logo">
                  <a href="{% url 'core:index' %}"><img src="{% static 'svg/logo2.svg' %}" alt=""></a>  
                </div>

                    <div class="navbar-list nav-list " id="navv">
                       <ul>
                           <li>
                            <div class="drop-btn list list-color">
                                <div class="c drop-one-1 black" data-sub="item1">  {% trans "Haqqımızda" %}  
                                    <span class="drop-down change-icon"><img src="{% static 'assets/' %}" alt=""></span>
                                </div>
                            </div>
                           </li>
                        
                       </ul> 
                       
                       <ul>
                           <li>
                                <div class="drop-btn open-list list list-color">
                                    <div class="c drop-one-1 black"  data-sub="item2">{% trans "Bizneslər" %}
                                        <span class="drop-down change-icon"><img src="{% static 'svg/arrow-black.svg' %}" alt=""></span>
                                    </div>
                                </div>
                           </li>   
                       </ul>
                        
                       <ul>
                           <li>
                                <div class="drop-btn list list-color black">
                                    <a href="{% url 'core:innovations' %}">{% trans "Yeniliklər" %}</a>
                                </div>
                           </li>
                       </ul>
                        
                        <ul>
                            <li>
                                <div class="drop-btn list list-color black">
                                    <a href="{% url 'core:career' %}">{% trans "Karyera" %}</a>
                                </div>
                            </li>
                            
                        </ul>
                        
                        <ul>
                            <li>
                                <div class="drop-btn list list-color black">
                                    <a href="{% url 'core:contact' %}">{% trans "Əlaqə" %}</a>
                                </div>
                            </li>
                            
                        </ul>
                        
                
                        <div class="submenu wrapper" id="item1">
                            <ul class="menu-bar">
                                <div class="menu-one"> 
                                    <div class="list-area">
                                        <div class="change-img">
                                            {% header_categories as context %}
                                            {% for s in context.korporativcategory %}
                                            <div class="card3" data-bg="{{s.image.url}}">
                                                {% if s.title == "Şirkət tarixçəsi" or s.title == "Company history" or s.title == "История компании"  %}
                                                <a href="{% url 'core:korporative' %}#history">{{s.title}}</a>
                                                {% elif s.title == "Komandamız" or s.title == "Our team" or s.title == "История компании" %}                                                
                                                <a href="{% url 'core:korporative' %}#leadership">{{s.title}}</a>
                                                {% elif s.title == "Missiyamız" or s.title == "Our mission" or s.title == "Наша миссия" %}
                                                <a href="{% url 'core:korporative' %}#ourmission">{{s.title}}</a>
                                                {% endif %}
                                            </div>
                                            {% endfor %}
                                        </div>

                                        <div class="corporative">
                                            <h4>{% trans "Haqqımızda" %}</h4>
                                            <p>{% trans "Keyfiyyət təkcə bizim standartımız deyil. Bu, həm də şirkətimizə aşılanmış bir münasibətdir." %} 
                                            </p>
                                        </div>
                                    </div>
                                
                                    <div class="img-box3">
                                       
                                    </div>
                                </div>
                            </ul>
                        </div>


                        <div class="submenu wrapper2" id="item2">
                            <div class="menu-bar2">
                                <div class="menu-one"> 
                                    <div class="list-area">
                                        <div class="change-img">
                                            {% header_category as context%}

                                            {% for i in context %}

                                            <div class="card2" data-bg="{{i.sector_image.url}}">
                                                <a href="{{i.get_absolute_url}}">{{i.title}}</a>
                                            </div>
                                            {% endfor %}
                                        </div>

                                        <div class="corporative">
                                            <h4>{% trans "Bizneslər" %}</h4>
                                            <p>{% trans "İllərdir sübut olunmuş təcrübə ilə bu gün İnşaat, Təchizat və Dam örtükləri sahələrində fəaliyyət göstəririk." %}</p>
                                        </div>
                                    </div>
                                
                                    <div class="img-box">
                                       
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="menu bar">
                        <span class="menu-global menu-global-black menu-top"></span>
                        <span class="menu-global  menu-global-black menu-middle"></span>
                        <span class="menu-global  menu-global-black menu-bottom"></span>
                      </div>

                    <div class="lang  change-lang-color">
                        <li class="button-dropdown">
                            <div class="lang">
                            <form action="{% url 'set_language' %}" method="post">  {#2#}
                                {% csrf_token %}  {#3#}
                                <select name="language" class="lng">  {#4#}
                                    {% get_current_language as LANGUAGE_CODE %}  {#5#}
                                    {% get_available_languages as LANGUAGES %}  {#6#}
                                    {% get_language_info_list for LANGUAGES as languages %}  {#7#}
                                    {% for language in languages %}
                                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>  {#8#}
                                            {{ language.local }} {{ language.code }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </form>
                        </div>
                        </li>
                    </div>
              
            </div>
        </nav>
  
    </header>

   

    
    <section class="inn-title">
        <div class="my-container">
            <div class="innovations-title color-b">{% trans "Yeniliklər" %}</div>
        </div> 
    </section>

   

    <section class="innovations-gray">
        <div class="my-container">
           
            <div class="innovation-details-title">
                <div class="number-date">
                    <div class="dates dates-edit edit2">
                        <div class="number">{{innovations.created_at.day}}</div>
                        <div class="date">{{innovations.created_at|date:"F" }} <br> {{innovations.created_at|date:"Y"}}</div>
                    </div>
                </div>

                <div class="line"></div>

                <div class="details-title">
                    <h1>{{innovations.title}}</h1>
                    <p>{{innovations.description}}</p>
                </div>
            </div>


            <div class="innovation-details-img-area">
                {% thumbnail innovations.news_image "1540x800" crop="center" as im %}
                    <img src="{{ im.url }}" width="1540" height="800">
                {% endthumbnail %}
            </div>

            <div class="innovation-details-text">
                <p class="details-text">{{innovations.content|safe}}</p>

                    <hr>

                    <div class="share-div">
                        <div class="share">
                            <p>{% trans "Paylaşın" %}</p>
                            <idiv class="share-icons">
                                <img src="{% static 'svg/fb.svg' %}" alt="">
                                <img src="{% static 'svg/in.svg' %}" alt="">
                            </idiv>
                        </div>
                        
                    </div>
                </div>
        
        </div>
    </section>

    <footer>
        <div class="my-container">
            <div class="footer-content">
                <div class="copyright">
                    © {% trans "Başak Group 2022. Bütün haqqları qorunur." %}
                </div>

                <div class="socials">
                    <a href="https://www.instagram.com/bashakgroup.az"><img src="{% static 'svg/instagram.svg' %}" alt=""></a> 
                    <a href="https://www.facebook.com/bashakgroup.az"><img src="{% static 'svg/facebook.svg' %}" alt=""></a> 
                    <a href="https://www.linkedin.com/company/basak-group"><img src="{% static 'svg/linkedin.svg' %}" alt=""></a> 
                 </div>

                <div class="powered-by">
                   <a href=""><img src="{% static 'svg/powered-by.svg' %}" alt=""></a> 
                </div>
            </div>
        </div>
    </footer>



    



    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" ></script>
   
    <script src="{% static 'js/main.js' %}"></script>

    <script>
		const body = document.querySelector(".sectors-background");
		const li = document.querySelectorAll(".card7");

		li.forEach(el => {
			el.addEventListener("mouseover", () => {
				let bg = el.getAttribute("data-bg");
				body.style.background = `url(${bg})no-repeat center /cover`;
			});
		});

    
	</script>

    <script>
        $(document).ready(function () {
            c = $("input[name='csrfmiddlewaretoken']").val();
    
            $(".lng").on("change", function () {
                lng = $(this).val();
                $.ajax({
                    url: "{% url 'set_language' %}",
                    method: 'POST',
                    data: {language: lng, csrfmiddlewaretoken: c},
                    success: function () {
                        location.reload();
                    },
                    error: function (e) {
                        $("body").html(e.responseText);
                    }
                })
            });
    
        });
    </script>


</body>
</html>

core/templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">
      ×
      </button>
      <strong>{{message}}<strong>
    </div>
 {% endfor %}
{% endif %}